#
# Task Planner
# Copyright (C) 2024 Mateusz Kubiak
# 
# Licensed under the GNU General Public License v3. 
# See LICENSE or visit <https://www.gnu.org/licenses/>.
#

name: taskplanner

volumes:
  db:

services:

  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    volumes:
      - db:/var/lib/mysql

  dbadmin:
    image: phpmyadmin:5.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - PMA_HOST=taskplanner-mysqldb-1
      - PMA_PORT=$MYSQLDB_DOCKER_PORT
    ports:
      - $DBADMIN_EXPOSE_PORT:80

  rabbitmq:
    image: rabbitmq:4.0-management-alpine
    ports:
      - 8080:15672
    env_file: ./.env
    environment:
      - RABBITMQ_DEFAULT_USER=$RABBIT_USER
      - RABBITMQ_DEFAULT_PASS=$RABBIT_PASS

  gateway:
    build: ./gateway
    restart: on-failure
    env_file: ./.env
    ports:
      - $GATEWAY_EXPOSE_PORT:8080
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  # services

  task-service:
    depends_on:
      - mysqldb
    build: ./services/task-service
    restart: on-failure
    env_file: ./.env
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  auth-service:
    depends_on:
      - mysqldb
    build: ./services/auth-service
    restart: on-failure
    env_file: ./.env
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  user-service:
    depends_on:
      - mysqldb
    build: ./services/user-service
    restart: on-failure
    env_file: ./.env
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true