#
# Task Planner
# Copyright (C) 2024 Mateusz Kubiak
# 
# Licensed under the GNU General Public License v3. 
# See LICENSE or visit <https://www.gnu.org/licenses/>.
#

version: "3.8"

services:

  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - PMA_HOST=taskplanner-mysqldb-1
      - PMA_PORT=$MYSQLDB_DOCKER_PORT
    ports:
      - $PHPMYADMIN_LOCAL_PORT:$PHPMYADMIN_DOCKER_PORT

  gateway:
    build: ./gateway
    restart: on-failure
    env_file: ./.env
    ports:
      - $GATEWAY_LOCAL_PORT:$GATEWAY_DOCKER_PORT
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  task-service:
    depends_on:
      - mysqldb
    build: ./task-service
    restart: on-failure
    env_file: ./.env
    ports:
      - $TASK_LOCAL_PORT:$TASK_DOCKER_PORT
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  user-service:
    depends_on:
      - mysqldb
    build: ./user-service
    restart: on-failure
    env_file: ./.env
    ports:
      - $USER_LOCAL_PORT:$USER_DOCKER_PORT
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
